/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MeuPrimeiroProjeto;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
// comentário de linha
    public static void main(String[] args) {
        System.out.println("Ola mundo");
    }
    /*
    Bloco de comentario 
    de varias linhas
    
    */
    
    /**
     * comentário de documentação
     */
}
