/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VariaveisTiposOperadores;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       int idade = 0; // numeros inteiros 
       float cotacaoDolar = 5.0f; // até 6 casas decimais
       double cotacaoEuro = 6.0d; // até 10 casas decimais
       char genero = 'M'; // uma letra
       byte ponto = 0; //
       boolean estaCadastrado = false; // true or false
       
       String nome = "esse é um texto pequeno"; // para armazenar texto
    }
}
